# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: StandardCode.StandardCode
PackageVersion: 0.1.3
InstallerLocale: en-US
InstallerType: portable
Commands:
  - standardcode
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/admin001-bit/standardcode/releases/download/v0.1.3/standardcode-windows-x64.exe
    InstallerSha256: 4be5a45a1d60517f403a9257b140db25c27cc4ae35d4e80ac916e4afa5864c33
ManifestType: installer
ManifestVersion: 1.12.0
