# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: StandardCode.StandardCode
PackageVersion: 0.1.1
InstallerLocale: en-US
InstallerType: portable
Commands:
  - standardcode
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/admin001-bit/standardcode/releases/download/v0.1.1/standardcode-windows-x64.exe
    InstallerSha256: 4543a23cc5e27bd3a581d2b0e5316552686de6090ca0a881ce52d6b936380317
ManifestType: installer
ManifestVersion: 1.10.0
